# -*- coding: utf-8 -*-
TITLE="DD-254 Interactive — User Manual"
SUB="Preparing, validating, issuing and tracking DD Form 254"
VER="Covers build v190 (tool version 2.116)"

DOC = [
("h1","1. What this tool is"),
("p","DD-254 Interactive is a single HTML file that runs entirely inside your browser. There is no server, no login and no network traffic: everything you type stays on the machine you typed it on, in that browser's local storage. Opening the file from a different browser, a different Windows profile, or a colleague's laptop shows an empty workspace."),
("p","Two consequences follow, and they govern everything else in this manual:"),
("n","Your drafts and templates are only as safe as your last backup. Nothing is stored anywhere else. Section 9 explains how."),
("n","The tool is single-user by design. Two people cannot collaborate inside one file. Managers consolidate a team by importing each person's backup read-only — section 8."),
("warn","The DD Form 254 itself may only be UNCLASSIFIED or CUI. Classified content is conveyed through attachments referenced in Items 13 and 14, never typed into the form. Never attach classified material to the validation log."),

("h1","2. Before you start"),
("h2","2.1 Set the classification marking"),
("p","The top bar carries a <b>Classification when filled in</b> selector. Leave it at UNCLASSIFIED, or switch to CUI. This drives the banner at the top and bottom of the screen, the marking stamped on every page of every exported PDF, the marking on the first row of every exported CSV, and the encryption warning shown when you record distribution."),
("h2","2.2 Flag a SAP DD-254"),
("p","Beside the classification selector is a <b>SAP DD-254</b> toggle. Leave it off unless this form is administered under a Special Access Program. It is off by default and it never prints on the form."),
("p","Everything in the tool that cites DoDM 5205.07 — most visibly the requirement that a subcontractor's authorised representative countersign Item 17 — appears only when this is set. Those are Special Access Program rules; on an ordinary subcontract they do not apply, and the tool no longer raises them."),
("h2","2.3 One tab only"),
("p","If you open the tool in a second tab or window, that tab goes read-only and shows a full-screen notice. This is deliberate. Template lists are saved as a whole, so two tabs editing at once would silently destroy one another's work with no error message."),
("p","The read-only tab offers <b>Use this tab instead</b>, which hands the lock over and puts the other tab into read-only mode, and <b>Reload</b>. If a tab crashes, its lock expires after a few seconds and the next tab reclaims it automatically."),
("h2","2.4 Where the work lives"),
("p","The tool has two views. The <b>DD-254 Workspace Dashboard</b> is your queue — every DD-254 you are working on. The form itself takes one DD-254 at a time. Opening a draft from the dashboard takes you into the form with that record loaded, and <b>Dashboard</b> at the top left goes back."),

("h2","2.5 Settings"),
("p","<b>Manage</b> then <b>Settings</b> opens a panel of preferences. It replaces the draft list while it is open, and closing it brings the list back. The panel is built from the tool\u2019s own registry of settings rather than a fixed list, so what you see is what this build actually supports."),
("tbl",[["Setting","What it controls"],
        ["Form layout","<b>One page</b> puts every wizard step on the page at once. <b>Step by step</b> shows one step at a time. The floating form button and this row always agree."],
        ["Item 13 layout","<b>One block</b> is the classic free-text box. <b>Sections</b> gives a box per ticked Item 10 or 11 entry \u2014 see 4.17."],
        ["Theme","Light or dark. Dark applies to the tool chrome only: the DD-254 facsimile, the print stylesheet and every export are untouched."],
        ["Workspace width","Reading, wide, full-window or a custom width set by dragging the dashboard edge. It changes the workspace only, never the DD-254 facsimile."],
        ["Text size","Compact, standard or large text for the application workspace. It does not change the form or exported documents."],
        ["Backup reminder","How many unsaved changes may accumulate before the reminder warns you. The default reproduces the previous behaviour, and it cannot be switched off entirely."],
        ["Your name","Recorded on template packs and read by the manager rollup. Changeable here without clearing site data."],
        ["Export filename","Which fields make up an exported file name, in what order, with which separator \u2014 see 6.5."]]),
("note","Dark theme is deliberately absent from anything printed or exported. A reviewer opening your PDF sees the same document whichever theme you work in."),
("h1","3. The dashboard — working your queue"),
("h2","3.1 Reading a card"),
("p","Each DD-254 is a card. The coloured border around the card is its status. A card turns grey once a revision or final has been spawned from it — grey means superseded, and the live status has moved to the newer card indented beneath it."),
("p","The card line shows the contract number, the contractor, and — when Item 7b is filled — <b>Subcontractor CAGE</b>."),
("h2","3.2 Statuses"),
("tbl",[["Status","Meaning"],
        ["Draft","Being prepared. Forced automatically whenever validation errors exist."],
        ["Blocked","Waiting on someone else, or on an approval. Requires a documented hold — see 3.6 and 3.7."],
        ["Ready to sign","Complete and validated, awaiting certification."],
        ["Issued","Signed and distributed."],
        ["Skipped","Solicitations only. The customer went straight to an Original, so this solicitation was never issued and never will be. Counted under Issued as closed-out work."],
        ["Cancelled","Any stage. Requires a documented reason. Leaves the working list — see 3.6."]]),
("p","The chips along the top count each status and act as filters — click one to show only those cards, click again to clear. They run in the order work moves: <b>Draft, Blocked, Ready to sign, Issued, Cancelled</b>, then Total and the average draft-to-issue time. Skipped folds into the Issued chip."),
("note","<b>Awaiting info was retired.</b> It meant the same thing as Blocked and split the queue for no reason. Any record still sitting on it is moved to Blocked when the dashboard loads, keeping its holds and history, and the change is written to the audit log."),
("h2","3.3 Stages and the revision chain"),
("p","A record carries a stage: Solicitation, Original, Revision or Final. From a Solicitation you can spawn an Original; from an Original or Revision you can spawn a Revision or a Final. Spawned cards nest under their parent, keeping the whole chain for one contract together. <b>Compare</b> shows a field-by-field difference against the parent."),
("p","A spawned child inherits the form content and the ongoing work — NISS verification, to-dos, notes and the validation log. It does not inherit anything that happened to the parent: holds, distribution records, countersignature, issue date, review date, or permission to bypass validation."),
("h2","3.4 Copying a DD-254"),
("p","<b>Copy</b> asks which kind you want, because copying means two different things."),
("tbl",[["Choice","What comes across"],
        ["Full copy","Everything, including holds, distribution record and countersignature. Right when the new form is the same work in a new place and those are all still live questions. Notes and to-dos start clean."],
        ["Copy and reset the workflow","The dashboard face stays exactly as it is \u2014 title, contract, contractor, notes, to-dos, NISS verification, the whole form. Only the workflow events clear: status, holds, distribution, countersignature, issue date, review date and the validation override. Right when the paperwork is correct but this is a fresh run of it."]]),
("note","Neither carries an issue date. An inherited one would be a plain falsehood, and it feeds the portfolio export and the draft-to-issue average. The reset uses the same routine a spawned revision uses, so \u201creset the workflow\u201d means the same thing everywhere."),
("p","<b>Resetting later.</b> You do not have to decide at copy time. A card carrying workflow history shows a <b>Reset workflow</b> button, so a full copy you have already started working can be cleaned up without copying again and losing everything done since. It is the same reset, with a confirmation listing exactly what will go."),
("n","Kept: the form, your notes, to-dos and NISS verification."),
("n","Cleared: status, holds, distribution records, countersignature, issue date, review date and the Draft override."),
("warn","A record that states something already happened \u2014 <b>Issued</b>, <b>Cancelled</b>, <b>Skipped</b> \u2014 cannot be reset. Clearing the distribution record off a DD-254 that went out the door does not make it unissued; it only makes the tool lie about it. Copy it and reset the copy instead."),
("note","Resetting is not a way past an approval hold. Any Item 10, 11 or 14 box still ticked raises its hold again immediately and the card returns to Blocked. The reset clears the workflow, not the reasons for it."),
("h2","3.5 Status is gated by validation"),
("p","You cannot move a card out of Draft while it has validation errors; the status snaps back. Tick the override checkbox on the card to permit a status regardless of missing fields. Cancelling and skipping are exempt — those are exactly the moments a form is incomplete."),
("p","Records that already record something that happened — <b>Issued</b>, <b>Cancelled</b>, <b>Skipped</b> — are left alone by autosave. Opening an old issued DD-254 after a rule change will not quietly demote it to Draft; it went out the door, and the tool does not rewrite that. Setting a status by hand still runs the full gate."),
("h2","3.6 Holds — recording why something is stuck"),
("p","Setting a card to Blocked requires a reason. You cannot skip it: the status will not change until you type one, and cancelling returns the card to its previous status."),
("p","The reason is stored as a hold and appears in a red panel on the card face, visible without opening anything. Each hold records the status that raised it and the date. Tick a hold to resolve it; the badge flips from a red open-hold count to a green <b>holds cleared</b>. You can add further holds from the panel without touching the status."),
("p","Issuing with an open hold is possible but challenged — you are shown the outstanding holds and must confirm, and the override is written to the audit log."),
("h2","3.7 Approval holds — the stop that makes you think"),
("p","Some boxes on a DD-254 cannot be flowed to a contractor on your say-so alone; somebody outside this tool has to approve them. When you tick one, the tool raises an <b>approval hold</b> and moves the card to Blocked."),
("p","This is not the tool refusing to issue. It is a deliberate stop that makes you ask the questions worth asking: do we hold this authority, how did we get it, and what permits us to release this part of the DD-254 to a subcontractor. Sometimes the answer is that you already hold standing authority. That is a perfectly good answer \u2014 it just has to be written down."),
("tbl",[["Box","What it is","Who approves"],
        ["10a","COMSEC information","GCA"],
        ["10c","CNWDI","GCA"],
        ["10e(1)","Sensitive Compartmented Information","Senior Intelligence Officer"],
        ["10e(2)","Non-SCI intelligence information","GCA"],
        ["10f","Special Access Program information","Program Security Officer"],
        ["10g","NATO information","GCA"],
        ["10h","Foreign Government Information","GCA"],
        ["11i","TEMPEST requirements","GCA, on a CTTA determination"],
        ["11j","OPSEC requirements","GCA"],
        ["11k","Defense Courier Service","GCA"],
        ["Item 14","Additional security requirements","GCA"]]),
("n","The hold reads, for example: <i>Item 10a COMSEC information checked \u2014 GCA approval required before issue. Record approving authority, date and reference.</i>"),
("n","While any approval hold is open the DD-254 <b>cannot reach Ready to sign or Issued</b>. Attempting it returns the card to Blocked and lists what is outstanding."),
("n","The validation override checkbox does <b>not</b> clear an approval hold. An override that could wave away an approval gate would defeat the only thing the gate is for."),
("n","Clearing one asks how. Four common answers are offered as one-click starting points \u2014 standing authority you already hold, a GCA response, approval carried by the prime DD-254, or not required and why \u2014 and each fills a text box you complete. A one-word clearance is refused."),
("n","Un-ticking the box does not delete the hold. It is marked <b>superseded</b>, so the record still shows the box was once checked and why it stopped applying."),
("note","Ticking 11i or 11j automatically sets Item 14 to YES, so those raise two holds rather than one. That is correct: both need answering."),
("p","Every raise, clearance and supersession goes to the audit log, so the Notes Report and the audit CSV together show what was approved, by whom, and on what basis."),
("h2","3.8 Cancelling and skipping"),
("p","<b>Cancelled</b> is available at any stage and demands a reason. The reason, the date, and the status it was cancelled from are recorded and shown on the card. Cancelled work drops out of the working list; click the Cancelled chip to see it. A chain only disappears when the whole chain is cancelled — cancelling a solicitation does not hide a live Original spawned from it."),
("p","<b>Skipped</b> appears in the dropdown only on Solicitation cards. Use it when the customer dropped the solicitation and later came straight to an Original. Spawning never sets it for you; you mark the solicitation Skipped or Issued yourself."),
("h2","3.9 Notes and to-do items"),
("p","Click <b>Notes</b> on a card to expand its panel. <b>Notes</b> is free text and appears in the Notes Report and the Manager Rollup. <b>To-do</b> items are the running “I need…” list; each requires a note-taken date, and any item can be turned into an Outlook calendar reminder dated to that note."),
("h2","3.10 Finding things"),
("p","The search box matches far more than the title: contract number, contractor, CAGE, GCA, every text field on the form including Block 13, note text, hold and cancellation text, and both the number and the name of every checked Item 10 and 11 box. Searching <b>10a</b> and searching <b>COMSEC</b> return the same contracts. A match on a revision surfaces the whole chain it belongs to. You can also filter by requestor and by status, and sort by recent activity, date created, title or status urgency."),
("h2","3.11 NISS verification and countersignature"),
("p","<b>NISS</b> records that you verified the contractor's facility clearance and safeguarding. Click the badge, enter your initials, and the date and initials are stored. Issuing without it is possible but challenged. <b>Countersigned</b> records the date the signed form came back."),
("h2","3.12 What a card tells you at a glance"),
("p","Beside the stage chip, every card carries the DD Form 254\u2019s own classification marking \u2014 <b>UNCLASSIFIED</b> or a purple <b>CUI</b> \u2014 so you can see which forms have to be sent encrypted without opening them. This is the marking on the form itself, not the contract\u2019s clearance level."),
("p","A card also carries a <b>paperclip badge</b> counting everything that must travel with that DD-254: what its own selections require, what the template it was built from demands, and anything you recorded by hand. Click the badge to open the card on the full list, grouped by where each item came from. A form with nothing to attach shows no badge. The count is computed from the same source the distribution dialog uses, so the two can never disagree."),
("h2","3.13 Distribution"),
("p","Flagging a DD-254 <b>Issued</b> opens a distribution dialog built from that form's own Item 18 — each checked box becomes a row, 18f pulls in its address text, and the requestor gets its own separate row. Addresses are prefilled strictly from their own source: <b>18a from the Item 6 contractor FSO e-mail and nothing else</b>, 18b from the Item 7 subcontractor FSO, 18c from the 6c, 7c and 8c security office text. Every box is free text with a picker holding every address the form knows, so you can correct anything."),
("note","If Item 6 carries no FSO e-mail, <b>18a is left blank</b> rather than guessed at. A blank row makes you look; a wrongly prefilled one invites a send. Drafts created before the Item 6 and 7 FSO e-mail fields existed will therefore show a blank 18a — their old addresses are still one click away in the row’s picker."),
("p","Everything defaults to ticked; untick what has not gone yet and log it later."),
("tbl",[["Button","What happens"],
        ["Record distribution","The ticked rows are logged and the DD-254 is issued."],
        ["Skip for now","The DD-254 is <i>still issued</i>; <b>issued-without-distribution</b> goes to the audit log and you log the recipients later from the card."],
        ["Cancel the issuance","The DD-254 is <b>not</b> issued. The status goes back where it was, no issue date is set and nothing is recorded, with <b>issue-cancelled</b> written to the audit log."]]),
("note","Pressing Escape cancels the issuance rather than skipping. Dismissing a dialog should never be the action that puts a DD-254 out the door."),
("n","Cancelling a re-issue leaves the original issue date alone \u2014 only a date this transition would have set is cleared."),
("p","The dialog also lists <b>Attach before you send</b> — the documents your selections require, anything the language template demands, and your own free-text notes — with a copy button. If the form is marked CUI it carries a red <b>SEND ENCRYPTED</b> banner citing DoDI 5200.48."),
("p","On the card, the <b>distributed</b> badge is a button: click it to expand straight to the distribution log, where each row shows the timestamp, party, recipient and method."),
("h2","3.14 Review dates"),
("p","DoDI 5220.22 requires a review every two years. When you issue a Revision (Item 3b) the tool offers to set the review date two years from the revision date and can produce a calendar invite. The card badges the date, amber near due and red once overdue. The clock applies to revisions only."),
("h2","3.15 Recount validation"),
("p","The error and warning counts on each card are a snapshot written when a draft is saved, not recomputed as you look at the dashboard. Whenever the validation rules change, every stored draft keeps showing numbers derived from the old rules until you open it."),
("p","<b>Manage</b>, then <b>Recount validation (all drafts)</b> walks every draft, re-checks it against the current rules, refreshes the counts, and puts back whatever you had open. Nothing else about the drafts is touched. Run it after any tool update."),

("h1","4. The form — preparing the DD-254"),
("p","The form is an eight-step wizard with a live validation panel down the right-hand side. Steps are not locked: use Next and Previous, or the step dots, to move freely."),
("tbl",[["Wizard step","Items covered"],
        ["Step 1","1a, 1b, 2, 3, 4, 5 — levels, contract numbers, form type"],
        ["Step 2","6, 7, 8 — contractor, subcontractor, performance locations"],
        ["Step 3","9 — unclassified description"],
        ["Step 4","10 — access requirements (12 boxes)"],
        ["Step 5","11 — performance requirements (13 boxes)"],
        ["Step 6","12, 13, 14, 15 — public release, security guidance, additional requirements, inspections"],
        ["Step 7","16, 17 — GCA and certification"],
        ["Step 8","18 — required distribution"]]),
("h2","4.1 Two ways to work the form"),
("p","The form opens as a guided walk \u2014 eight steps, one at a time. The button at the top right of the progress bar switches to <b>one page</b>, where every section is on a single scrolling page. The choice is remembered between sessions, and switching back lands you on the step you were on."),
("p","Step by step is right the first few times. Once you know the form, paging through eight cards to change one field is friction; use one page. Both views are the same form \u2014 nothing is hidden in either."),
("p","The numbered dots carry a live badge: a red count where that section has outstanding errors, a green tick once a section you have passed is clean. They read the same error list the right-hand panel uses, so a step you have not opened yet still tells you it needs attention."),
("h2","4.2 The instruction panels"),
("p","Every item has a collapsible <b>Instructions</b> panel carrying the conditional rules for that item, colour-coded REQUIRED, RECOMMENDED and DO NOT. They open automatically the first time you visit a step. Read them; they carry rules this manual only summarises."),
("p","Rule-backed red and amber alerts beneath the form items show an <b>Authority:</b> footer naming the DD Form 254 instruction or governing source used for the rule. An organisation-specific safeguard that is not a regulatory mandate is labelled <b>Workflow control:</b> instead. The footer explains the finding; it does not change its severity or validation effect."),
("h2","4.3 The right-hand validation panel"),
("tbl",[["Section","What it shows"],
        ["Errors","Blocking problems. The form cannot leave Draft while any exist."],
        ["Item 3 rules","Rules specific to Original, Revised or Final."],
        ["Recommendations","Non-blocking warnings and reminders."],
        ["Flow-down obligations","What a prime may and may not impose on a subcontractor."],
        ["Applicable clauses","FAR and DFARS clauses triggered by your selections."],
        ["Item 13 needed","Which selections require language in Block 13."],
        ["E-mail distribution","Addresses harvested from the form — see 4.11."],
        ["Attachment reminder","Documents that must travel with the form."],
        ["Completion status","Error and warning counts, and rough progress."]]),
("h2","4.4 Which fields the tool insists on"),
("p","The form marks required fields with a red asterisk. A field that is required <i>and</i> empty is also shaded red on the form itself, so you can find it without reading the error list. The shading clears the moment you fill it in."),
("p","The tool only enforces the fields <b>you</b> are responsible for as the preparer. It does not enforce Item 16 or Item 17."),
("tbl",[["Field","When it is required"],
        ["1a, 1b","Always \u2014 clearance and safeguarding levels."],
        ["2a","When a subcontract number is entered in 2b."],
        ["Item 3 date","Always. Which date depends on the form type: 3a original, 3b revision, 3c final."],
        ["Item 4","Only when you mark this a follow-on contract."],
        ["Item 5","Only when retention is claimed \u2014 then both the request date and the authorised period."],
        ["6a, 6b, 6c","Always \u2014 contractor name and address, CAGE, cognizant security office."],
        ["7 FSO e-mail","Once a subcontractor exists. The DD-254 has to reach them."],
        ["Item 9","Always \u2014 the unclassified description."],
        ["Item 12 Q1","Always \u2014 DIRECT or THROUGH. If THROUGH, the routing office must be named."],
        ["Items 14, 15","When marked YES, the narrative that the YES promises."],
        ["10k, 11m","When \u201COther\u201D is checked, the specify field."]]),
("note","<b>Items 16 and 17 are deliberately not enforced.</b> The GCA block and the certification block are completed by the Government Contracting Activity and the certifying official after you hand the form over. Blocking your draft on somebody else\u2019s fields would stop the tool doing its job. Their asterisks remain on screen as a reminder of what the finished form needs, but a blank Item 16 or 17 will never raise an error or shade red."),
("n","Complete Items 17h Signature and 17i Date Signed in the generated PDF; they do not appear in the browser."),
("warn","Errors matter beyond the panel. A form with errors cannot leave Draft, and the exported PDF is stamped DRAFT. Clearing the error list is what makes a form issuable."),

("h2","4.5 Step 1 — Items 1 to 5"),
("h3","Item 1a — FCL level required"),
("p","Confidential, Secret or Top Secret. Verify it in NISS or NCAISS before you rely on it — a CAGE code is not evidence of a cleared facility. Do not cite special categories here; Restricted Data, COMSEC, SCI and SAP belong in Item 10."),
("h3","Item 1b — Safeguarding level at the contractor facility"),
("p","None, N/A, Confidential, Secret or Top Secret."),
("b","It may never be higher than Item 1a. The tool blocks this outright."),
("b","If Item 11a is checked — access only at another facility — it must be None or N/A."),
("b","If 11b, 11c or 11d is checked it must carry a classification level, not None."),
("h3","Item 2 — This specification is for"),
("p","2a prime contract number, 2b subcontract number, 2c solicitation or other number with a due date. Mark one primary type, but 2a and 2b may both carry entries on a subcontract form. Entering anything in 2b makes 2a mandatory."),
("p","A separate DD Form 254 is required for every subcontract at every tier. Where services span multiple contracts, enter <b>Multiple Contracts</b> rather than a number; other contract-related numbers belong in Item 13."),
("h3","Item 3 — This specification is"),
("p","Original (3a), Revised (3b) or Final (3c), each with its own date; a revision also carries a revision number. Do not revise solely to exercise an option year or to update POC information in 16d, 16f, 17a or 17g."),
("h3","Items 4 and 5 — Follow-on and Final"),
("p","Item 4 identifies a preceding contract. Item 5, when YES, requires the contractor's formal request date, the GCA-authorised retention period, and final disposition instructions in Item 13. The tool checks Item 13 for disposition language and clears the error once it finds it — the built-in Item 5 template satisfies it."),
("h2","4.6 Step 2 — Items 6, 7 and 8"),
("h3","Item 6 — Contractor"),
("p","6a name and address, 6b CAGE, 6c cognizant security office, plus an optional <b>contractor FSO e-mail</b>. Fill the block from the Facility template library by typing a CAGE code into the filter above 6a. A SAM.gov lookup sits beside the CAGE field."),
("h3","Item 7 — Subcontractor"),
("p","7a name and address, 7b CAGE, 7c CSO, a <b>required subcontractor FSO e-mail</b>, and an optional <b>classified mailing address</b>. The e-mail is a blocking error once a subcontractor exists — the form has to reach them. Address format is deliberately not policed, so group aliases and multiple addresses are accepted."),
("h3","Item 8 — Actual performance locations"),
("p","Use <b>+ Add Performance Location</b> for multiple sites. Each carries the location, CAGE, CSO, an optional FSO e-mail and an optional classified mailing address. Listing a location limits all classified performance to the locations listed, so list every one."),
("b","If Item 11a is checked, Item 8a is required."),
("b","If classified work happens at the Item 6a address, enter <b>See Item 6a</b> rather than repeating it."),
("b","If inspections will be by anyone other than the DCSA CSO, complete Item 15."),
("note","The FSO e-mail and classified mailing address fields are workflow only. They never print on the DD Form 254. The e-mails feed the FSO send list and the distribution record; the mailing addresses are written into Item 13 — see 4.10."),
("h3","Applying a saved facility or location"),
("p","When you fill Item 7 or an Item 8 location from a template, a red <b>CONFIRM</b> banner appears directly beneath the address. Saved details go stale: verify the address, the CAGE and the FSO name and e-mail against NISS before issuing. Typing by hand never raises it, and it clears when the form is cleared."),
("h2","4.7 Step 3 — Item 9"),
("note","A DD-254 created as a <b>Solicitation</b> opens Item 9 with <b>***FOR SOLICITATION PURPOSES ONLY***</b> on its own line, so a reader meets that before the description. Type the description beneath it."),
("n","Spawning an Original from that solicitation removes the marker \u2014 an award is not for solicitation purposes only. Your description is kept."),
("n","The marker does not count as a description. A solicitation carrying only the marker still reports Item 9 as empty."),
("p","A plain-language unclassified description. Never use classified project names, code words, or descriptions that are themselves classified."),
("h2","4.8 Step 4 — Item 10, access requirements"),
("p","Twelve boxes: 10a COMSEC, 10b Restricted Data, 10c CNWDI, 10d FRD, 10e(1) SCI, 10e(2) non-SCI intelligence, 10f SAP, 10g NATO, 10h FGI, 10i ACCM, 10j CUI, 10k Other. The interactions the tool enforces:"),
("b","10c CNWDI requires 10b Restricted Data."),
("b","10f SAP forces Item 14 to YES and requires Item 15."),
("b","10e(1) SCI requires Item 15 to name the Senior Intelligence Officer."),
("b","10k Other requires the specify field."),
("b","10a COMSEC with accountable material stored at the contractor also needs 11h. Accessed only at a government facility, it does not."),
("b","10j CUI applies only when a classified contract also carries CUI requirements."),
("h3","Access Eligibility Advisor"),
("p","The advisor beneath Item 10 compares Items 1a, 1b, 10 and 11 with a verification snapshot. It looks for potential contradictions involving SCI, SAP, NATO, CNWDI, RD/FRD, COMSEC, FGI, ACCM, CUI, foreign or NATO recipients, SAPF or SCIF status, and the Item 11l classified-access basis."),
("p","Every finding shows the authority or guidance used for the comparison. The source set includes 32 CFR Part 117, the DD Form 254 Instructions, DoDM 5105.21 Volume 3, DoDM 5205.07, DoDI 5200.48 and DoDM 5200.01 Volume 3."),
("note","The advisor is informational only. It never enters Live Validation, adds an error or warning, changes status, blocks issuance, or changes the exported DD Form 254. Verify actual eligibility and safeguarding in NISS and retain the supporting record."),
("h2","4.9 Step 5 — Item 11, performance requirements"),
("p","Thirteen boxes. The mutually exclusive combinations are enforced as hard errors:"),
("b","11a — access only at another facility — excludes 11b, 11c, 11d, 11h, 11i and 11k."),
("b","11b — receive and store documents only — excludes 11a, 11c, 11d, 11h, 11i and 11k."),
("b","11c and 11d each exclude 11a and 11b."),
("p","11e services only is not recommended alongside 11b, 11c or 11d; use 11m instead, and explain in Item 13 if you keep both. Other consequences: 11f overseas requires Item 13 detail and forces Item 18d; 11g requires DD Form 1540; 11i TEMPEST and 11j OPSEC each force Item 14 to YES; 11l is expected only alongside 10j."),
("warn","A prime may not impose TEMPEST, OPSEC or Defense Courier use on a subcontractor without prior GCA written approval. The Flow-down panel lists every selection carrying this constraint, and compares a spawned child against its parent: a clearance or safeguarding level above the prime's is a blocking error."),
("h3","Item 11 Performance Advisor"),
("p","The advisor beneath Item 11 cross-checks each selected 11a through 11m block against Items 1b, 10, 13, 14 and 18. Questions shown for the selected blocks capture the evidence behind the choice, including access locations, classification guidance, storage, overseas coordination, DTIC sponsorship, COMSEC account authority, TEMPEST or OPSEC direction, Defense Courier approval, CUI designation and other written authority."),
("note","These questions and findings are part of the draft's verification record but are excluded from official PDF data. Like the Access Eligibility Advisor, they never create validation errors, change status or block issuance."),
("h2","4.10 Step 6 — Items 12 to 15"),
("h3","Item 12 — Public release"),
("p","Q1 is the release routing, DIRECT or THROUGH — marking it is expected and the tool reminds you. Q2 is the release authority: office name, phone and e-mail where available. Q2 is optional and leaving it blank raises nothing."),
("h3","Item 13 — Security guidance"),
("p","The substance of the form. The editor accepts bold and underline for on-screen readability; the exported form is always plain text. Buttons above the field insert standard paragraphs, laid out as a heading and a blank line:"),
("p","<font face='Courier'>Reference 10a:<br/><br/>Access to classified COMSEC information requires…</font>"),
("p","Write in plain language, be specific, and name the item you are expanding on. Every document cited here must reach the contractor. Do not copy NISPOM text in verbatim, and avoid citing internal GCA directives — extract the relevant portions as attachments."),
("p","The tool scans Block 13 for references and compares them against your selections. A reference to a box you have not checked is a blocking error, wherever it appears in the text — <b>10a</b>, <b>10A:</b>, <b>Ref 10a</b> and <b>Reference 10A</b> all register. Genuine cross-references stay inert: <b>See Item 10a for guidance</b> and <b>Ref. 10a: N/A</b> raise nothing."),
("h3","Items 14 and 15"),
("p","Item 14 covers requirements over and above NISPOM — YES is required for 10f, 11i and 11j, and may be required for 11f. Item 15 covers inspections, and is required for SAP, for SCI (naming the Senior Intelligence Officer), and whenever inspections are by anyone other than the DCSA CSO."),
("h2","4.11 Steps 7 and 8 — Items 16, 17 and 18"),
("p","Item 16 is the GCA block, 16a to 16f. The browser captures Items 17a through 17g from Certifier templates; 17e is for subcontracts only. Complete 17h Signature and 17i Date Signed in the generated dynamic PDF."),
("n","Neither block is enforced by the validation panel — see 4.3. You can complete and issue a form with both left empty."),
("p","Item 18 is the required distribution: 18a contractor FSO, 18b subcontractor FSO, 18c cognizant security office, 18d overseas activity, 18e ACO, 18f other with a free-text field. 18d must be checked whenever 11f is checked, and 18b on any subcontract form. What you tick here becomes the checklist presented when you record distribution."),
("h2","4.12 Classified mailing addresses"),
("p","If the subcontractor or a performance location holds a separate classified mailing address, put it in that block's optional field. The tool maintains a matching section at the bottom of Item 13:"),
("p","<font face='Courier'>Classified Mailing Address (Beta Corp):<br/>PO Box 0000<br/>Anytown, ST 00000</font>"),
("p","Each entry is labelled with whose it is. Edit an address and the block rewrites in place; clear one and only that entry goes; clear them all and the block disappears. Text you have written above it is never touched."),
("h2","4.13 The e-mail distribution panel"),
("p","Three groups. <b>1 — CSO and requestor</b> collects addresses from the 6c, 7c and 8c security office text plus the requestor field. <b>2 — FSOs</b> lists the contractor, subcontractor and location FSO e-mails automatically, with a manual box beneath for anyone not covered by Items 6, 7 or 8. <b>3 — per DD-254 requirement</b> picks up addresses in Item 13 and Block 18f."),
("p","Each address is listed once, under the first group it belongs to. If the FSO group shows <b>already listed above</b>, the address is recorded as a CSO or requestor contact rather than missing."),
("h2","4.14 The source and validation log"),
("p","A working record, separate from the form and never printed on it. Log the item, the source consulted, what was confirmed and the date. Files can be attached and each is fingerprinted with a SHA-256 hash. It exports as its own PDF with attachments embedded."),
("warn","Attach only UNCLASSIFIED or CUI files. Attachments are embedded in the browser workspace, in saved draft files, and in the exported log PDF."),

("h2","4.15 Item 13 has three managed regions"),
("p","Item 13 is still one block of text you can type into freely, but three regions of it are written and rewritten by the tool. They keep the order below, and each is rewritten in place rather than appended, so editing a value never stacks a second copy."),
("tbl",[["Region","Where it comes from","Where it sits"],
        ["Supported effort line","The effort number under Item 2","The very top"],
        ["Your text and inserted language","You, and the template libraries","The middle"],
        ["Classified mailing addresses","Item 7 and each performance location","Below your text"],
        ["CUI designation block","The fields under Item 18","The tail, after five blank rows"]]),
("p","<b>The supported effort line.</b> A field under Item 2 takes a number. Entering one writes a line at the top of Item 13; changing it rewrites that line; clearing it removes the line and leaves the rest intact. If you move the line down the block by hand, it is rewritten where you put it. The number never reaches an official form field."),
("p","<b>The CUI designation block.</b> Fields under Item 18 build a labelled block at the foot of Item 13. Filling any one field writes every label, leaving the others blank. Clearing them all removes the block and its blank rows. Rows print in a fixed order, not the order you filled them."),
("p","Standard Language and Contract Type templates respect these regions: inserted language lands below the effort line and above the CUI block, and a Contract Type template that replaces Item 13 loses neither."),
("h2","4.16 Limited dissemination controls and distribution statements"),
("p","Two pickers feed the CUI designation block."),
("p","<b>Limited dissemination controls.</b> Ten controls, each with its marking. Tick any number; they print alphabetised by marking and slash-separated, so the order you tick them cannot change what appears. Three \u2014 REL TO, DISPLAY ONLY and DL ONLY \u2014 take a list, and the list box appears only while that control is ticked. A list-bearing control with nothing typed yet prints as its bare marking, never a placeholder."),
("p","<b>Distribution statements.</b> Six statements, A to F. A and F take no reason for control; the others offer only the reasons their statement permits. Switching statement drops a reason that is no longer valid and keeps one that still is. Statement C assembles around its fill-ins; F takes a controlling office and a date. An unfilled slot leaves no stray separator, and a missing controlling office stays visibly unfilled rather than silently vanishing."),
("note","Neither the dissemination controls nor the distribution statement is written into an official form field. They exist to build the Item 13 designation block."),
("h2","4.17 Item 13 in sections layout"),
("p","With <b>Item 13 layout</b> set to <b>Sections</b> you get one box per ticked Item 10 or 11 entry instead of a single block. Typing in a box writes through to the real Item 13 immediately: there is one store, and the boxes are a view of it. Unticking an Item 10 or 11 box removes its complete managed section from Item 13 even when the section contains language, so stale guidance cannot create a reverse-reference error."),
("p","The removed section is kept briefly as an undo record. <b>Put back</b> rechecks the item and restores its wording; otherwise the removed language does not print or remain in the draft."),
("p","Each section is written as its reference, a blank line, then the text. Sections land in form order regardless of the order you write them, and rewriting one replaces it in place. Prose you typed outside any section is never touched."),
("p","The raw Item 13 field stays visible in this layout as a failsafe, and editing it directly is authoritative \u2014 the boxes follow. Switching layout never alters the stored text."),
("p","In sections layout the Item 10 and 11 template cards move out of the side panel into the section boxes themselves, each offering insert and save. Language for other items stays in the side panel as before."),
("h2","4.18 Setting a validation flag aside"),
("p","A finding you have considered and judged not to apply can be set aside. It needs an open draft and a written reason; a dismissal without one is refused. The finding stays visible, struck through, with your reason attached, and stops counting toward the blocking total. Putting it back restores the count."),
("p","Every dismissal is written to the audit log with its reason, author and time. If the underlying rule is later reworded, the tool asks for your judgement again rather than carrying the old one forward."),
("warn","A dismissal cannot clear a compliance hold. Approval gates are not findings and are not dismissible."),
("h2","4.19 Two panels, not one"),
("p","The right-hand column holds two separately scrolling panels: validation output in one, the things you act on in the other. Collapsing hides both."),
("h1","5. Templates — building them and using them"),
("p","Eight libraries live under <b>Templates</b> on the dashboard. All are local to this browser and all are included in the Full Backup."),
("tbl",[["Library","Holds","Fills"],
        ["Facility","Item 6 address, CAGE, FSO e-mail, linked 6c CSO","6a, 6b, 6c, FSO e-mail"],
        ["CSO","Security office name, address, phone, e-mail","6c, 7c, 8c"],
        ["Performance / Sub","Location, CAGE, CSO, FSO e-mail, classified mailing address","7a-c, 8a-c and their extras"],
        ["Certifier","Name, title, address, CAGE, phone, e-mail of the official who certifies the form","17a-g"],
        ["Contract Type","A whole DD-254 posture, offered when a draft is created","10, 11, 12, 13, 14, 15, 16, 18"],
        ["DD-254 Template Language","The same, insertable piece by piece from the form","10, 11, 12, 13, 14, 15, 16, 18"],
        ["Security Managers","Name, e-mail, program","Assigned to a language template"],
        ["Standard Language","Recurring text your organisation puts on its own DD-254s","13"]]),
("h2","5.1 Working the template tables"),
("n","<b>Add</b> appends a blank row. Typing is saving; there is no save button."),
("n","The up and down arrows reorder the list, which is the order the dropdowns show."),
("n","The red cross deletes a row. <b>Undo last change</b> puts it back — one level, and it covers row deletions as well as spreadsheet uploads."),
("n","<b>Done</b> returns to the dashboard and flushes anything pending."),
("p","Give every row a Label; that is what you see in the dropdown. In Facility and Performance / Sub, the CSO dropdown <i>links</i> a row to a CSO template rather than copying its text, so correcting the CSO once corrects everything using it."),
("note","Duplicate CAGE codes across rows are flagged as you type. Two rows with the same CAGE usually means one is stale."),
("h2","5.2 Saving from the form into a template"),
("p","You do not have to build the tables up front. Fill a form once, then push what you typed into the library."),
("tbl",[["Where you are","What to click","Where it lands"],
        ["Item 7 filled in","Save this sub-contractor to Performance/Sub templates","Performance / Sub"],
        ["An Item 8 location filled in","Save this location to Performance/Sub templates","Performance / Sub"],
        ["A whole form you want to reuse","Capture from form, in the language manager","DD-254 Template Language"]]),
("p","Saving carries the FSO e-mail and the classified mailing address with the entry, and links the CSO automatically when the 8c text still matches a CSO template. Editing that text by hand drops the link rather than asserting something false. Re-saving with a field left blank never wipes what is already stored."),
("p","Performance and subcontractor locations are also harvested automatically: every time you leave the form for the dashboard, any location you typed is added if it is not already there. Placeholder text such as <b>See Item 6a</b> is ignored."),
("note","Item 6 has no save-to-template button. Build facility entries in the Facility library directly, or import them by spreadsheet."),
("h2","5.3 Applying a template into a form"),
("b","Item 6 — type a CAGE code into the facility filter above 6a. It fills 6a, 6b, the linked 6c and the FSO e-mail."),
("b","6c, 7c and 8c — each carries an apply CSO template dropdown above the field."),
("b","Items 7 and 8 — the Performance / Sub search fills location, CAGE, CSO, FSO e-mail and classified mailing address together."),
("b","Item 17 — the certifying-official dropdown above 17a fills all seven fields."),
("b","A whole posture — the Contract type dropdown on the dashboard card applies a Contract Type template. It ticks Items 10, 11 and 18, sets the Item 12 routing, fills 14, 15 and 16, and writes Block 13. See 5.6."),
("h2","5.4 Building a DD-254 Template Language entry"),
("p","A single entry carries language for twelve items at once — what you reach for when a programme has a standard security posture you issue repeatedly."),
("n","Dashboard, then Templates, then DD-254 Template Language, then <b>Add</b>."),
("n","Name it for the posture, and set the <b>Source date</b> — the version date of the authority the language came from, not today. Until you set it the entry shows a red NO SOURCE DATE badge everywhere."),
("n","Assign a <b>Security manager</b>; it searches the Security Managers library."),
("n","<b>Edit blocks</b> to set the form\u2019s own classification (UNCLASSIFIED or CUI) and fill Items 10 and 11 (each ticked box opens a text area for Block 13 language tied to that box), 12, 13, 14, 15, 16, 18, and a free-text list of required attachments."),
("p","Every box in Items 10, 11 and 18 is shown with its full name, not just its number \u2014 10j reads <i>Controlled Unclassified Information (CUI)</i>. The wording is read from the form itself, so a template can never label a box differently from the DD-254 it will be applied to."),
("note","The classification here is the marking on the DD Form 254 itself, which may only be UNCLASSIFIED or CUI. Applying a template sets it on the form and repaints the banner, and the marking then shows on the dashboard card. A spreadsheet row asking for anything higher falls back to UNCLASSIFIED rather than storing a marking the form cannot carry."),
("p","<b>Capture from form</b> snapshots the open form instead. It never overwrites your per-checkbox language or the attachment list, because neither exists on the form."),
("warn","Capture takes Block 13 as one block of text. If you had previously applied a different template to that form, its language is now in Block 13 and will be captured. Capture from a clean form, or check Block 13 straight afterwards."),
("p","On the form, select an entry in the Template language panel to see its content as cards. <b>Insert all of this template</b> sits at the top and applies every section in one go \u2014 the classification, the Item 10, 11 and 18 boxes, the Item 12 routing, Blocks 13, 14, 15 and 16. Fields the template leaves blank are not touched, so nothing already on the form is wiped, and it asks first if Block 13 already has text. Beneath it each section still has its own insert or apply button if you want only part of it. Nothing is applied automatically. Per-checkbox language inserts itself into Block 13 as you tick the matching box and removes itself if you untick it. The required attachments appear in the attachment reminder and again in the distribution dialog."),
("h2","5.5 Contract Type templates"),
("p","A Contract Type template holds exactly the same content as a DD-254 Template Language entry, and is built in the same editor. The two differ only in <i>when</i> they are used: a Contract Type is offered as a whole when you create a draft, and can be applied later from the Contract type dropdown on the card; a Template Language entry is inserted piece by piece from the form\u2019s side panel."),
("n","Dashboard, then Templates, then Contract Type, then <b>Add</b> \u2014 or <b>Capture from form</b> to snapshot a form you have already built."),
("p","Applying one ticks the Item 10, 11 and 18 boxes, sets the Item 12 routing and its office, fills 14, 15 and 16, and writes Block 13 \u2014 the free text first, then the language attached to each ticked box. Its required attachments appear in the attachment reminder and again in the distribution dialog, exactly as a Template Language entry\u2019s do."),
("note","A field left blank in the template never wipes what the draft already has. Applying a Contract Type over a form that already carries Block 13 text asks first."),
("warn","Neither library carries Block 2a. A contract number belongs to one specific contract, so it has no place in a template that exists to be reused \u2014 it was removed from both."),
("p","Contract Type templates saved by an earlier build held only a name and Block 13 text. That text now sits in the Block 13 field of the fuller editor and everything else starts empty; nothing was lost, and the entries keep working as they did."),

("h2","5.6 Standard Language"),
("p","Some organisations put the same wording on every DD-254 they issue. This library keeps that text in one place so it goes on identically every time, instead of being retyped or pasted from the last form."),
("n","Two fields only: a <b>Name</b> and the <b>text</b>. Nothing about the form is modelled here."),
("n","<b>Nothing is applied automatically.</b> The form\u2019s side panel lists your saved entries; you pick one and click <b>Insert</b>. Organisations keep several and use different ones on different contracts."),
("n","Inserted text goes to the very top of Block 13 \u2014 above the Item 10 and 11 box language and above anything you have typed."),
("n","Insert more than one and they read in the order you added them."),
("n","The same entry cannot be inserted twice. The panel marks what is already in Block 13."),
("warn","Removing standard language is a <b>manual edit</b>: delete it from Block 13 yourself. Once deleted it stays deleted \u2014 nothing puts it back on the next validation pass. This is ordinary text once inserted, not a region the tool maintains."),
("p","What a DD-254 is carrying shows on its card, under the attachment list. It is there so you can see it without opening the form; it never blocks a status."),
("note","<b>Capture from form strips it.</b> If you capture a form that has standard language showing, the captured template holds only what you wrote. Otherwise the text would be baked into that template untracked, and the same wording could later be inserted a second time and print twice on an issued form."),
("n","<b>Insert all</b> in the DD-254 Template Language panel does not touch this library."),
("n","In the full backup. Not in the spreadsheet round trip, and not in dashboard search."),

("h2","5.7 Spreadsheet round trip"),
("p","All eight libraries export to CSV and re-import from CSV or XLSX."),
("n","Export first, even from an empty library — the header row is the layout the importer expects."),
("n","Edit in Excel. Keep the header row and the ID column; the ID is how a row is matched rather than duplicated."),
("n","Upload. Nothing is applied yet: a preview reports what will be updated, added, skipped and unmatched."),
("n","Confirm. Deleting unmatched entries is offered but guarded — removing more than half the list makes you type DELETE."),
("n","<b>Undo last change</b> reverts it. One level only."),
("note","Row 1 of an exported CSV carries the classification marking. The importer skips it automatically, so exported files re-import unchanged."),

("h2","5.8 Saving Item 13 language back to a template"),
("p","Wording you have refined on a form can be pushed back into the library it came from. Choose the template first \u2014 saving with none chosen, or with nothing to save, is refused. Item 11 language lands in the Item 11 map and Item 10 language in the Item 10 map; they do not cross."),
("p","If the template already holds language for that item you are asked before it is replaced, and declining leaves it alone. Saving the same wording twice does not prompt, because nothing would change. In sections layout the save button on a section box saves the text actually in that box."),
("h1","6. Producing the form"),
("tbl",[["Export","Use"],
        ["Official DD-254 (PDF)","The official expanding XFA form. It is watermarked DRAFT while errors remain and signs in Acrobat Pro — see 6.2."],
        ["Preparer's Worksheet","Internal checklist of what is required, recommended and outstanding."],
        ["Contracting Officer Package","A preparatory checklist for eligibility, safeguarding, guidance, distribution and clause-applicability review."],
        ["Validation Log (PDF)","Your sources and evidence, with attachments embedded."],
        ["Print","Browser print of the on-screen form."]]),
("h2","6.1 Contracting Officer Package"),
("p","The Contracting Officer Package is a <b>preparatory review aid</b>, not an official form and not a substitute for the signed DD Form 254 or the contract file. It checks entity eligibility and safeguarding capability separately; Item 12 public-release routing; Item 13 clarity, currency and supporting documents; CUI contract direction; original, revised, final and solicitation actions; Items 14 and 15; and minimum signed distribution."),
("warn","Its clause section is an <b>applicability review</b>, not a complete clause matrix. A DD Form 254 box does not by itself prescribe a FAR or DFARS clause. The contracting officer must confirm the current regulation, agency supplement, acquisition type, COTS status, location and personnel facts, and actual subcontract performance before incorporating or flowing down clauses."),
("p","For CUI, the requiring activity identifies the CUI through the contracting vehicle. If Controlled By, category, distribution statement or LDC, or the point of contact is missing, the package reports the gap and tells the reviewer to obtain written direction rather than invent a value."),
("h2","6.2 Digital signatures"),
("p","<b>Open the generated dynamic PDF in Adobe Acrobat Pro and complete Items 17h Signature and 17i Date Signed there; the browser does not collect or prefill them.</b> The export has been tested against a pristine blank copy of the form; both sign the same way."),
("warn","Acrobat Pro is what makes this work. The dynamic export loses the Adobe Reader Extensions that the official form ships with, because building the file rewrites it rather than appending to it. Reader Extensions are what let <i>free</i> Adobe Reader fill and sign a form; Acrobat Pro does not need them. So anyone in your chain signing on free Reader rather than Pro will not be able to sign the dynamic export."),
("n","If Acrobat reports that the operation failed while still appearing to sign, close the file and reopen it, then check the signature panel actually lists the signature. Persisting a signature means writing to the file, and that write can fail when the PDF was opened straight from a download or temporary location. Save it to a normal folder and sign from there."),
("p","XFA is unsupported in browser and mobile PDF viewers, so open the official export in Adobe Acrobat rather than judging it in a browser preview. The former user-facing flattened export was removed; its old static builder remains test-only and is not a release output."),

("h2","6.3 How exported files are named"),
("p","Exports are named from the form \u2014 CAGE codes, the contract number, the stage. A slash in a contract number becomes a hyphen, so <b>12/32</b> is filed as <b>12-32</b> rather than being squashed to 1232, which would be a different contract number and would collide with a form genuinely numbered 1232."),
("n","Spaces are packed out of PDF names and kept as underscores where words matter. Characters that carry no meaning in a contract number \u2014 colons, asterisks, question marks \u2014 are dropped."),
("note","Files exported before this behaviour existed keep their old names; nothing is renamed retrospectively."),
("h2","6.4 Consistent output formatting"),
("p","The official dynamic PDF and the internal regression builder use one shared set of formatters. The second path is retained only as an independent test oracle, so the suite can catch a field that would otherwise print differently without exposing a second official export to users."),
("tbl",[["Field","How it prints"],
        ["Items 1a and 1b","Words, not shouting, and no instruction text: Top Secret, Secret, Confidential, None, N/A."],
        ["All dates","YYYY-MM-DD. Anything that is not eight digits passes through untouched, so \u201Csee contract\u201D still prints."],
        ["Phone numbers 16e and 17f","Digits only. Punctuation and a leading 1 are stripped; anything that is not a ten-digit number prints as typed."],
        ["CAGE codes 6b, 7b, 8b, 17e","Uppercase. The on-screen boxes also display uppercase as you type."],
        ["Item 13 text","Smart quotes, curly apostrophes, em dashes and ellipses are folded to plain characters that the PDF fonts can actually draw."],
        ["Reviewing officials","Internal reviewers are never printed. Only when there are more than six does an \u201CAdditional reviewing officials\u201D line appear in Item 13."]]),
("note","If a printed value looks wrong, fix it on the form rather than in the PDF. The official export is always regenerated from the stored form fields."),

("h2","6.5 Choosing how exported files are named"),
("p","<b>Manage</b> then <b>Settings</b> lets you build the export file name from the fields your organisation files by. The default reproduces the previous fixed convention exactly, so leaving it alone changes nothing."),
("b","Pick which boxes contribute, in what order, and which separator joins them. Items 6b, 7b and 8b are each offered on their own."),
("b","An empty box is skipped without leaving a separator behind, and if every box is empty the name falls back rather than producing an empty one."),
("b","Each box contributes at most 30 characters, and only the first line of a multi-line box, so a long combination still fits a usable path."),
("b","Hyphens inside a contract number are preserved rather than eaten by the separator."),
("note","A company that files by contract number alone, or by CAGE alone, can have exactly that. Corrupt or unrecognised stored settings fall back to the default instead of breaking the export."),
("h1","7. Manager functions"),
("h2","7.1 Manager rollup"),
("p","Because each person's tool is a separate island, managers consolidate by collecting Full Backup files and importing them together under <b>Manager Rollup</b>. The result is read-only and held only for that session — nothing is written into your own workspace, and closing the view discards it."),
("h2","7.2 Portfolio CSV"),
("p","A row per DD-254 with the full picture: stage, status, contract, contractor, clearance and safeguarding levels, CAGE, GCA, every Item 10 and 11 selection, error and warning counts, NISS, countersignature, issue and review dates, distribution count, open holds and their reasons, and the cancellation date, source status and reason."),
("p","This answers <i>which of our contracts involve X</i>. Filter the 10a or 11i column in Excel and you have every contract with COMSEC or TEMPEST without opening a draft. Cancelled work is included even though the dashboard hides it."),
("h2","7.3 Notes report and audit log"),
("p","The <b>Notes Report</b> is a printable per-draft summary of holds, to-do items and notes. The <b>Audit Log</b> records every material action — status changes, holds, cancellations, NISS verification, distribution, template uploads, restores, recounts — with timestamps, and exports to CSV."),

("h1","8. Data safety"),
("h2","8.1 Full backup"),
("p","<b>Templates</b>, then <b>Full Backup</b> writes a single JSON file containing every template library, every draft, and the audit log. The dashboard header counts changes since your last backup and turns red when you are behind."),
("p","Backups carry a SHA-256 checksum and entry counts. On restore both are verified: a truncated download or an edited file is refused rather than silently loaded. Older backups without a checksum require explicit confirmation. The audit log merges on restore rather than overwriting, de-duplicated by timestamp."),
("warn","Restoring a Full Backup REPLACES every template list. Drafts are merged by ID, but templates are not. Take a backup of the current state before restoring another one."),
("h2","8.2 Sharing templates with colleagues"),
("p","When one person curates the libraries for a team, <b>Manage, then Share templates</b> moves them between instances. <b>Export templates only</b> writes a file containing the eight libraries and <i>nothing else</i> \u2014 no drafts, no dashboard, nothing about anybody\u2019s actual DD-254s. The file is stamped with who exported it and when."),
("p","<b>Export templates only</b> opens a picker before it writes anything. Every library is listed with its entries, all ticked, so sharing the lot is still one click \u2014 but you can untick a whole library, or individual entries within one, and send only what is useful. Sharing two new Standard Language paragraphs need not drag your entire facility list along with them."),
("n","A running count shows how many of your templates are selected. A partly ticked library shows as such. Selecting nothing is refused rather than writing an empty file."),
("p","<b>Import templates from a colleague</b> shows what would change before anything is applied, library by library, and you tick which to take."),
("tbl",[["What arrives","What happens"],
        ["A template you imported before, since edited","Updated in place. Recognised by a hidden identifier, so it works even if either of you renamed it."],
        ["A template identical to one you already hold","Skipped silently. Not a conflict, and it does not clutter the preview."],
        ["A brand new template","Added."],
        ["The same NAME as one of yours, but different text and a different origin","<b>Both are kept.</b> Yours is untouched; theirs arrives renamed \u2014 for example <i>Bob (from Alice, 2026-08-08)</i>."]]),
("note","The last row is the only genuinely ambiguous case: two people independently created a template with the same name. Neither is more correct, so nothing is discarded. Delete whichever you do not want \u2014 that takes one click, whereas recovering wording that was silently overwritten takes a backup you may not have."),
("warn","<b>Facility</b> and <b>Performance / Sub</b> are unticked by default. Those describe your own sites and your own subcontractors, so a curator\u2019s copy is usually wrong for everyone else. Tick them only if you mean to."),
("n","<b>Undo last change</b> in any library reverts that library\u2019s import. One level, as everywhere else."),
("n","Every import and export is written to the audit log, including who the pack came from."),
("h2","8.3 Storage"),
("p","The dashboard footer shows local storage in use. Drafts and templates live in the browser's local database; if that is unavailable the tool falls back to a much smaller store and warns you when it fills. If you see a storage-full warning, take a Full Backup immediately — unsaved changes are held in memory only."),

("h2","8.4 The audit log and chain of custody"),
("p","The audit log is no longer capped at 5,000 entries and no longer competes for the small storage bucket \u2014 it lives in the drafts database. If a cap is ever reached, the log records that entries were removed rather than losing them silently."),
("p","Deleting a draft is recorded, and cancelling the confirmation records nothing. Deleting a record that has revisions or finals spawned from it warns you and names the descendants first."),
("p","A full backup carries its own checksum for the history, separate from the checksum over the form data, so an older backup still verifies."),
("h2","8.5 Spreadsheet exports cannot carry formulas"),
("p","Any cell that would otherwise begin with a character a spreadsheet treats as a formula is neutralised on export, and the guard is stripped on import, so a round trip through the tool preserves every value. An apostrophe you typed yourself is preserved. This applies to dismissal reasons and free text as much as to fields."),
("h1","9. A day with the tool"),
("n","Open the tool in one tab. Check the backup indicator; if it is red, back up."),
("n","Scan the status chips. Work Blocked first — each carries a hold saying what it is waiting on, including any approval hold."),
("n","Open what needs action. Clear validation errors using the right-hand panel."),
("n","When a form is complete, verify the FCL in NISS and record it, then set Ready to sign."),
("n","On issue, record distribution when prompted. Attach everything the reminder lists, and send encrypted if the form is marked CUI."),
("n","Set the review date on revisions and take the calendar invite."),
("n","Back up before you close."),

("h1","10. Security posture"),
("p","This matters if the tool has to pass a security review, and the short answer is that none of it has to be taken on trust."),
("n","<b>It makes no network requests of its own.</b> The file contains no fetch, XMLHttpRequest, WebSocket, EventSource or sendBeacon call site, and loads nothing from the internet \u2014 no remote scripts, styles, fonts or images. One feature is a deliberate exception: the SAM.gov lookup opens a search URL carrying a value taken from the form."),
("n","<b>The browser constrains it</b>, rather than the tool merely asserting it. A Content Security Policy in the file\u2019s header sets <b>connect-src \u2018none\u2019</b>, so the browser refuses fetch, XMLHttpRequest, WebSocket and sendBeacon whatever the code attempts, and <b>form-action \u2018none\u2019</b> blocks posting anywhere. Two limits matter: the policy does not stop injected script, because the whole application is inline, and it does not cover ordinary navigation. Exfiltration is constrained, not blocked."),
("n","<b>It executes no dynamic code.</b> No eval, no new Function. The policy deliberately omits \u2018unsafe-eval\u2019."),
("n","<b>It installs nothing.</b> No administrator rights, no registry entries, no services, no scheduled tasks. It is a document opened in a browser tab."),
("n","<b>Data stays on the machine</b>, in browser IndexedDB with localStorage as a fallback. There is no account, no licence check and no telemetry."),
("p","Reference hyperlinks to public government sites \u2014 acquisition.gov, dcsa.mil, esd.whs.mil and others \u2014 open only when you click them. The page itself never contacts them."),
("note","Roughly 67% of the file is not application code: an open-source PDF library and two official DD Form 254 PDFs, both verifiable against their own sources. The separate security fact sheet gives hashes, verification commands and a procedure for reconstructing the file from independently sourced parts."),
("p","<b>Accessibility.</b> Every form control carries an accessible name, and the Item 10, 11 and 18 names are read from the form at runtime so a screen reader hears exactly what is printed beside the box. Interactive elements are keyboard operable."),
("h1","11. Notes and limitations"),
("h2","11.1 On cited rules and advisory findings"),
("p","The validation alerts and the two advisors identify the source used for each comparison. SAP-specific requirements attributed to DoDM 5205.07 appear only when the SAP DD-254 flag is on. The citations make a finding reviewable; they do not make the tool a substitute for the contract, the GCA, NISS, the responsible Government security authority, or the current text of the cited source."),
("p","Advisor findings are deliberately conservative prompts. A potential contradiction may have a documented fact or authority outside the DD Form 254 that resolves it. Verify the operational answer and retain that evidence rather than treating the screen as an eligibility determination."),
("h2","11.2 What the tool does not do"),
("b","It does not track DD Forms 254 <i>received</i> from customers, only those you issue."),
("b","It does not track Item 5 retention expiry; the only date-driven reminder is the biennial review."),
("b","It does not record a contract end date, so nothing prompts you to raise a Final."),
("b","A <b>Full copy</b> carries the source's holds, distribution log and NISS verification. <b>Copy and reset the workflow</b> keeps the form and NISS verification but clears the workflow events. Neither carries the issue date."),
("h2","11.3 Keeping this manual honest"),
("p","This manual is generated from a content file and a build script kept alongside the PDF. Every release that changes the HTML must update this source and rebuild both published copies of the manual; never patch the PDF by hand."),
]
